


export const ADD_LINE_ITEM = 'ADD_LINE_ITEM';
export const DELETE_LINE_ITEM = 'DELETE_LINE_ITEM';
export const UPDATE_TAX = 'UPDATE_TAX';
export const UPDATE_LINE_ITEM = 'UPDATE_LINE_ITEM';
export const UPDATE_INVOICE_NUMBER = 'UPDATE_INVOICE_NUMBER';



